// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: yokogcachepb/yokogcache.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	YokogCache_Get_FullMethodName = "/yokogcachepb.YokogCache/Get"
)

// YokogCacheClient is the client API for YokogCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type YokogCacheClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type yokogCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewYokogCacheClient(cc grpc.ClientConnInterface) YokogCacheClient {
	return &yokogCacheClient{cc}
}

func (c *yokogCacheClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, YokogCache_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// YokogCacheServer is the server API for YokogCache service.
// All implementations must embed UnimplementedYokogCacheServer
// for forward compatibility.
type YokogCacheServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedYokogCacheServer()
}

// UnimplementedYokogCacheServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedYokogCacheServer struct{}

func (UnimplementedYokogCacheServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedYokogCacheServer) mustEmbedUnimplementedYokogCacheServer() {}
func (UnimplementedYokogCacheServer) testEmbeddedByValue()                    {}

// UnsafeYokogCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to YokogCacheServer will
// result in compilation errors.
type UnsafeYokogCacheServer interface {
	mustEmbedUnimplementedYokogCacheServer()
}

func RegisterYokogCacheServer(s grpc.ServiceRegistrar, srv YokogCacheServer) {
	// If the following call pancis, it indicates UnimplementedYokogCacheServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&YokogCache_ServiceDesc, srv)
}

func _YokogCache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YokogCacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YokogCache_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YokogCacheServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// YokogCache_ServiceDesc is the grpc.ServiceDesc for YokogCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var YokogCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yokogcachepb.YokogCache",
	HandlerType: (*YokogCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _YokogCache_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "yokogcachepb/yokogcache.proto",
}
