mysql:
    host: localhost
    port: 3306
    database: testdb
    username: root
    password: 123456
    charset: utf8mb4

etcd:
    address: 
        - localhost:2379
        - localhost:22379
        - localhost:32379
    ttl: 5                  

services:
    yokogcache:
        name: Yokogcache
        addr:
            - localhost:8001
            - localhost:8002
            - localhost:8003
        ttl: 30              

domain:
    groupcache:
        name: Yokogcache